name: HEPFittingTutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-ecosystem-user-package-isolation
  - root<=6.24
  - pip:
      - jupyterlab
      - pandas
      - scipy
      - numpy
      - pyroofit
      - pyhf[contrib]
      - iminuit
      - mplhep
